# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

name: gefs_osn_stage3

jobs:
  docker:
    runs-on: arc-runner-eco4cast
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
    container:
      image: eco4cast/rocker-neon4cast:latest
      options: --memory 45g
    steps:
      - uses: actions/checkout@v4

      - name: Install
        shell: Rscript {0}
        run: |
          #install.packages("remotes")
          #devtools::install_deps(upgrade="never")
          #remotes::install_github("eco4cast/gefs4cast")
          #remotes::install_version('arrow', version = '20.0.0')
          
      - name: Download Pseudo
        shell: Rscript {0}
        run: |
          source("drivers/download_psuedo.R")

      - name: Update Stage3
        shell: Rscript {0}
        run: |
          source("drivers/update_stage3.R")

      - name: Healthcheck
        run: |
          curl -m 10 --retry 5 https://hc-ping.com/cfa6fee0-6608-46f4-9cca-4e83445788fe
